defmodule PhoenixKitWeb.EcommerceGettextManifest do
  @moduledoc false

  # Lists every translatable string used by `phoenix_kit_ecommerce` so that
  # `mix gettext.extract` records them into PhoenixKit core's POT, where
  # ecommerce translations live.
  #
  # `phoenix_kit_ecommerce` uses `PhoenixKitWeb.Gettext` as its Gettext
  # backend (via shop_web.ex), but the extractor doesn't walk into deps.
  # This manifest re-emits those gettext calls from core's own source so
  # the strings end up in `priv/gettext/default.pot` and can be translated
  # in every locale.
  #
  # ## Scope
  #
  # Admin-facing strings from all ecommerce admin LiveViews:
  # dashboard, carts, categories, category_form, products, product_form,
  # imports, import_show, settings, shipping_methods, shipping_method_form,
  # product_detail.
  #
  # Customer-facing storefront pages (user_orders, checkout, storefront)
  # are intentionally excluded — they use a separate translation strategy.
  #
  # The sidebar tab labels use a separate `PhoenixKitEcommerce.Gettext` backend
  # with its own `priv/gettext` in the ecommerce repo — that subsystem is OUT
  # of scope and must not be modified here.
  #
  # ## Refreshing the list
  #
  # When ecommerce admin adds or renames a translatable string, run:
  #
  #     grep -hEo '(gettext|ngettext)\("[^"]+' \
  #       lib/phoenix_kit_ecommerce/web/dashboard.ex \
  #       lib/phoenix_kit_ecommerce/web/carts.ex \
  #       lib/phoenix_kit_ecommerce/web/categories.ex \
  #       lib/phoenix_kit_ecommerce/web/category_form.ex \
  #       lib/phoenix_kit_ecommerce/web/products.ex \
  #       lib/phoenix_kit_ecommerce/web/product_detail.ex \
  #       lib/phoenix_kit_ecommerce/web/product_form.ex \
  #       lib/phoenix_kit_ecommerce/web/imports.ex \
  #       lib/phoenix_kit_ecommerce/web/import_show.ex \
  #       lib/phoenix_kit_ecommerce/web/settings.ex \
  #       lib/phoenix_kit_ecommerce/web/shipping_methods.ex \
  #       lib/phoenix_kit_ecommerce/web/shipping_method_form.ex \
  #     | sort -u
  #
  # This module is never called at runtime — it exists purely as an
  # extraction target for `mix gettext.extract`.

  use Gettext, backend: PhoenixKitWeb.Gettext

  @doc false
  def __extract__ do
    [
      gettext("= Category specific,"),
      gettext("= Global"),
      gettext("Abandoned"),
      gettext("About CSV Import"),
      gettext("Actions"),
      gettext("Active"),
      gettext("Active Products"),
      gettext("Active — Category and products visible"),
      gettext("Add"),
      gettext("Add Category"),
      gettext("Add Category Option"),
      gettext("Add Method"),
      gettext("Add Option"),
      gettext("Add Option or Value"),
      gettext("Add Product"),
      gettext("All Categories"),
      gettext("All Images Migrated"),
      gettext("All Status"),
      gettext("All Types"),
      gettext("All values"),
      gettext("Analyze & Configure"),
      gettext("Archived"),
      gettext(
        "Are you sure you want to delete %{count} categories? This action cannot be undone.",
        count: 0
      ),
      gettext("Are you sure you want to delete %{count} products? This action cannot be undone.",
        count: 0
      ),
      gettext("Are you sure you want to delete this import log?"),
      gettext("Are you sure you want to delete this product?"),
      gettext("Attached"),
      gettext("Auto-add"),
      gettext("Auto-detect (first product with image)"),
      gettext("Auto-generated"),
      gettext("Auto-generated from name"),
      gettext("Auto-generated from title"),
      gettext("Available Options"),
      gettext("Available Product Options"),
      gettext("Base Price"),
      gettext("Basic Information"),
      gettext("Billing module settings"),
      gettext("Blue"),
      gettext("Brand or manufacturer"),
      gettext("CSV Import"),
      gettext("CSV Import Filters"),
      gettext("Cancel"),
      gettext("Cancel Migration"),
      gettext("Cancelled %{count} pending migration jobs", count: 0),
      gettext("Cannot retry: file no longer exists"),
      gettext("Carts"),
      gettext("Carts will appear here when customers add items"),
      gettext("Categories"),
      gettext("Categories in shop disabled"),
      gettext("Categories in shop enabled"),
      gettext("Category"),
      gettext("Category Icons"),
      gettext("Category Image"),
      gettext("Category Name Display"),
      gettext("Category Options"),
      gettext("Category created"),
      gettext("Category deleted"),
      gettext("Category description"),
      gettext("Category display setting updated"),
      gettext("Category icon setting updated"),
      gettext("Category image"),
      gettext("Category name"),
      gettext("Category updated"),
      gettext("Change Image"),
      gettext("Change Parent"),
      gettext("Change Status"),
      gettext("Charge tax on this product"),
      gettext("Clear selection"),
      gettext("Compare At"),
      gettext("Compare at Price"),
      gettext("Completed At"),
      gettext("Configure"),
      gettext("Configure Option Mappings"),
      gettext("Configure keyword filters and category rules for CSV product imports"),
      gettext(
        "Configure product filters shown on the storefront sidebar. Customers can filter by price, vendor, and product options."
      ),
      gettext("Configure shipping method details"),
      gettext("Configure your e-commerce store"),
      gettext("Confirm"),
      gettext("Confirm Import"),
      gettext("Constraints"),
      gettext("Converted"),
      gettext("Cost"),
      gettext("Cost per Item"),
      gettext("Created:"),
      gettext("Currency & Tax Settings"),
      gettext("Currency and tax configuration is managed in the"),
      gettext("Current Modifier"),
      gettext("Custom"),
      gettext("Custom Price"),
      gettext("Custom selection"),
      gettext("Create Category"),
      gettext("Create Method"),
      gettext("Create Product"),
      gettext("Create a new category"),
      gettext("Create a new product"),
      gettext("Create your first category to organize products"),
      gettext("Create your first product to get started"),
      gettext("Create your first shipping method to get started"),
      gettext("Currency"),
      gettext("Customer"),
      gettext("Date"),
      gettext("Default Price"),
      gettext(
        "Define options specific to this category. These override global options with the same key."
      ),
      gettext("Define options that apply to all products (size, color, material, etc.)"),
      gettext("Delete"),
      gettext("Delete Categories"),
      gettext("Delete Product"),
      gettext("Delete Products"),
      gettext("Delete associated media files (orphaned only)"),
      gettext("Delete this category?"),
      gettext("Delete this shipping method?"),
      gettext("Delivery"),
      gettext("Delivery & Status"),
      gettext("Delivery in 3-5 business days"),
      gettext("Description"),
      gettext("Description:"),
      gettext("Digital"),
      gettext("Digital Product"),
      gettext("Digital Products"),
      gettext("Display category cards above products in the main shop page"),
      gettext("Download Limit:"),
      gettext("Download images to Storage"),
      gettext("Downloadable products"),
      gettext("Draft"),
      gettext("Draft Products"),
      gettext("Drag CSV file here or click to browse"),
      gettext("E-Commerce"),
      gettext("E-Commerce Settings"),
      gettext("Edit"),
      gettext("Edit %{name}", name: ""),
      gettext("Edit %{title}", title: ""),
      gettext("Edit Option"),
      gettext("Edit category details"),
      gettext("Edit product details"),
      gettext("Editable"),
      gettext("Enable stock tracking for products (Phase 2)"),
      gettext("Enabled"),
      gettext(
        "Enter an existing option key to add a new value, or a new key to create a new option."
      ),
      gettext("Error"),
      gettext("Error: %{reason}", reason: ""),
      gettext("Errors"),
      gettext("Est. days (max)"),
      gettext("Est. days (min)"),
      gettext("Existing products with the same slug are updated"),
      gettext("Expired"),
      gettext("Expiry:"),
      gettext("Failed"),
      gettext("Failed to add filter"),
      gettext("Failed to create import log"),
      gettext("Failed to delete category"),
      gettext("Failed to delete import log"),
      gettext("Failed to delete product"),
      gettext("Failed to delete shipping method"),
      gettext("Failed to read CSV file headers"),
      gettext("Failed to remove filter"),
      gettext("Failed to reset filters"),
      gettext("Failed to update category display setting"),
      gettext("Failed to update category icon setting"),
      gettext("Failed to update filter"),
      gettext("Failed to update filter label"),
      gettext("Failed to update inventory setting"),
      gettext("Failed to update setting"),
      gettext("Featured Product (image fallback)"),
      gettext("File"),
      gettext("File:"),
      gettext("File is too large (max 50MB)"),
      gettext("Filename"),
      gettext("Filter"),
      gettext("Filter '%{key}' added", key: ""),
      gettext("Filter for '%{key}' already exists", key: ""),
      gettext("Filter removed"),
      gettext("Filters reset to defaults"),
      gettext("Final Price"),
      gettext("Folder icon"),
      gettext("Free above"),
      gettext("From Import"),
      gettext("Full Description:"),
      gettext("Global Product Options"),
      gettext("Gray"),
      gettext("Guest"),
      gettext("Handle"),
      gettext("Hidden"),
      gettext("Hidden — Category and products hidden"),
      gettext("How category names should be displayed in the sidebar"),
      gettext("Image"),
      gettext("Image Migration"),
      gettext("Images will be downloaded from CDN URLs and stored in the Storage module"),
      gettext("Import"),
      gettext("Import Configurations"),
      gettext("Import Details"),
      gettext("Import Filter"),
      gettext("Import History"),
      gettext("Import Information"),
      gettext("Import Language"),
      gettext("Import completed successfully!"),
      gettext("Import failed: %{reason}", reason: ""),
      gettext("Import in Progress"),
      gettext("Import language:"),
      gettext("Import log deleted"),
      gettext("Import not found"),
      gettext("Import products from CSV files"),
      gettext("Import runs in the background — you can leave this page"),
      gettext("Import started: %{filename}", filename: ""),
      gettext("Import: %{filename}", filename: ""),
      gettext("Imported"),
      gettext("Imported Option Prices"),
      gettext("Imported Products"),
      gettext("In Progress"),
      gettext("Invalid import ID"),
      gettext("Inventory tracking disabled"),
      gettext("Inventory tracking enabled"),
      gettext("Items"),
      gettext("Key"),
      gettext("Label"),
      gettext("Link to Global Option"),
      gettext("Made to Order:"),
      gettext("Make Root (No Parent)"),
      gettext("Manage your e-commerce store"),
      gettext("Max order"),
      gettext("Max weight (g)"),
      gettext("Merged"),
      gettext("Method"),
      gettext("Migrate %{count} Products", count: 0),
      gettext(
        "Migrate product images from external CDN URLs to the Storage module for better control and reliability."
      ),
      gettext("Migrated"),
      gettext("Min order"),
      gettext("Min weight (g)"),
      gettext("Modifier"),
      gettext("Move %{count} selected products to a category", count: 0),
      gettext("Move to Category"),
      gettext("Name"),
      gettext("Never"),
      gettext("New Category"),
      gettext("New Product"),
      gettext("New Shipping Method"),
      gettext("No"),
      gettext("No Category"),
      gettext("No carts found"),
      gettext("No categories found"),
      gettext("No category"),
      gettext("No category-specific options"),
      gettext("No filter (import all products)"),
      gettext("No icons"),
      gettext("No image"),
      gettext("No imports yet"),
      gettext("No limit"),
      gettext("No limits"),
      gettext("No max"),
      gettext("No min"),
      gettext("No options defined"),
      gettext("No parent (root category)"),
      gettext("No products found"),
      gettext(
        "No products with images in this category. Add product images to enable this option."
      ),
      gettext("No shipping methods"),
      gettext("No threshold"),
      gettext("Not authorized"),
      gettext("Only CSV files are accepted"),
      gettext("Only one file at a time"),
      gettext("Option"),
      gettext("Option '%{key}' created", key: ""),
      gettext("Option Key"),
      gettext("Option Prices"),
      gettext("Option added"),
      gettext("Option key and value are required"),
      gettext("Option removed"),
      gettext("Option updated"),
      gettext("Option value"),
      gettext("Options"),
      gettext("Original price"),
      gettext("Parent"),
      gettext("Parent Category"),
      gettext("Pending"),
      gettext("Physical"),
      gettext("Physical Products"),
      gettext("Please enter a value first"),
      gettext("Please select a CSV file first"),
      gettext("Position"),
      gettext("Preparing import..."),
      gettext("Preview: Merged Schema"),
      gettext("Preview:"),
      gettext("Price"),
      gettext("Price Calculation"),
      gettext("Price Range"),
      gettext("Price override is configured per-option in the options settings."),
      gettext("Pricing"),
      gettext("Product"),
      gettext("Product Details"),
      gettext("Product Images"),
      gettext("Product Options"),
      gettext("Product Type"),
      gettext("Product created"),
      gettext("Product deleted"),
      gettext("Product title"),
      gettext("Product updated"),
      gettext("Products"),
      gettext("Products are automatically categorized based on title or category name"),
      gettext("Products in this category will show these options:"),
      gettext("Products requiring shipping"),
      gettext("Products will use global options only"),
      gettext("Progress"),
      gettext("Quick Actions"),
      gettext("Refresh stats"),
      gettext("Remove"),
      gettext("Remove auto-created categories that have no products after import"),
      gettext("Remove this filter?"),
      gettext("Reorder failed: %{reason}", reason: ""),
      gettext("Required"),
      gettext("Requires Shipping:"),
      gettext("Reset to defaults"),
      gettext("Required field"),
      gettext("Results"),
      gettext("Retry"),
      gettext("Retrying import: %{filename}", filename: ""),
      gettext("Root Only"),
      gettext("SEO"),
      gettext("SEO-friendly URL for this language"),
      gettext("Search"),
      gettext("Search by email or session ID..."),
      gettext("Search categories..."),
      gettext("Search products..."),
      gettext("Select from Storage"),
      gettext("Set Active"),
      gettext("Set Archived"),
      gettext("Set Draft"),
      gettext("Set Hidden"),
      gettext("Set Unlisted"),
      gettext("Set parent for %{count} selected categories", count: 0),
      gettext("Settings"),
      gettext("Show Categories in Shop"),
      gettext("Show icons next to category names in sidebar"),
      gettext("Shipping Methods"),
      gettext("Shipping method created"),
      gettext("Shipping method deleted"),
      gettext("Shipping method updated"),
      gettext("Shopify or Prom.ua CSV format, max 50MB"),
      gettext("Shopping Carts"),
      gettext("Short product description"),
      gettext("Sidebar Display"),
      gettext("Skip Mapping"),
      gettext("Skip empty categories"),
      gettext("Skip empty categories (remove categories with no products after import)"),
      gettext("Skipped"),
      gettext("Slot Key"),
      gettext("Slug"),
      gettext("Something went wrong. Please try again."),
      gettext("Specifications"),
      gettext("Standard Shipping"),
      gettext("Start Import"),
      gettext("Started At"),
      gettext("Started migration for %{count} products", count: 0),
      gettext("Status"),
      gettext("Storage image has priority"),
      gettext("Storefront Filters"),
      gettext("Storefront filter updated"),
      gettext("Supported formats: Shopify, Prom.ua (auto-detected from file headers)"),
      gettext("Tags:"),
      gettext("Tax Settings"),
      gettext("Text fields will be imported to this language"),
      gettext("Time"),
      gettext("Timestamps"),
      gettext("Title"),
      gettext("Title:"),
      gettext("Total"),
      gettext("Total Products"),
      gettext("Track Inventory"),
      gettext("Tracking supported"),
      gettext(
        "Translate category content for different languages. The default language uses the main fields above."
      ),
      gettext("Translated category name"),
      gettext("Translated description"),
      gettext("Translations"),
      gettext("Truncate (single line)"),
      gettext("Type"),
      gettext("Type:"),
      gettext("URL Slug"),
      gettext("Unit (optional)"),
      gettext("Unlimited"),
      gettext("Unlisted"),
      gettext("Unlisted — Category hidden, products still visible"),
      gettext("Unlisted: products appear in search/catalog but category not in menu"),
      gettext("Unrecognized CSV format"),
      gettext("Update"),
      gettext("Update Category"),
      gettext("Update Method"),
      gettext("Update Product"),
      gettext("Update status for %{count} selected categories", count: 0),
      gettext("Update status for %{count} selected products", count: 0),
      gettext("Updated"),
      gettext("Updated:"),
      gettext("Upload"),
      gettext("Upload CSV File"),
      gettext("Used as category image when no Storage image is selected"),
      gettext("User"),
      gettext("Value"),
      gettext("Value '%{value}' added", value: ""),
      gettext("Value '%{value}' added to '%{key}'", value: "", key: ""),
      gettext("Value '%{value}' already exists", value: ""),
      gettext("Value '%{value}' already exists in '%{key}'", value: "", key: ""),
      gettext("Variant Images"),
      gettext("Vendor"),
      gettext("Vendor:"),
      gettext("View"),
      gettext("View Details"),
      gettext("Weight:"),
      gettext("Wrap (multi-line)"),
      gettext("Yes"),
      gettext("Your cost for profit calculation"),
      gettext("auto-generated if empty"),
      gettext("e.g., Mounting Type"),
      gettext("e.g., cm"),
      gettext("errors"),
      gettext("existing products"),
      gettext("failed rows"),
      gettext("filtered out"),
      gettext("in Storage"),
      gettext("items"),
      gettext("jobs"),
      gettext("legacy URLs"),
      gettext("new products"),
      gettext("with images"),
      gettext("%{count} carts total", count: 0),
      gettext("%{count} categories deleted", count: 0),
      gettext("%{count} categories updated", count: 0),
      gettext("%{count} categories updated to %{status}", count: 0, status: ""),
      gettext("%{count} methods configured", count: 0),
      gettext("%{count} products deleted", count: 0),
      gettext("%{count} products moved", count: 0),
      gettext("%{count} products updated to %{status}", count: 0, status: ""),
      gettext("%{count} selected", count: 0),
      ngettext("1 category", "%{count} categories", 1, count: 1),
      ngettext("1 day", "%{count} days", 1, count: 1),
      ngettext("1 product", "%{count} products", 1, count: 1),
      gettext("— Standalone (no mapping) —")
    ]
  end
end
