defmodule PhoenixKitWeb.PdfViewerController do
  @moduledoc """
  Serves `phoenix_kit_catalogue`'s vendored PDF.js viewer assets through
  the router.

  The catalogue PDF detail page embeds the viewer from `/_pdfjs/...`.
  Normally those bytes are served by a `Plug.Static` mount that
  `mix phoenix_kit.install` / `mix phoenix_kit.update` add to the host
  endpoint. That mount is fragile — a host that bumps the deps without
  re-running the task (or whose endpoint gets regenerated by a scaffold
  script) loses it, and the viewer iframe then 404s with a
  `NoRouteError`.

  This controller is the router-served fallback. Because it's wired in
  via `phoenix_kit_routes()` (the same mechanism behind `/file/...` and
  `/<prefix>/assets/...`), it's present on every host that mounts
  PhoenixKit at all — no endpoint patch required. When the endpoint
  `Plug.Static` mount *is* present it runs first (endpoint plugs precede
  the router), so this only handles the fall-through.

  Read-only: it streams files from the catalogue app's
  `priv/static/pdfjs/` and nothing else. Path traversal is rejected via
  `Path.safe_relative/1` plus an expanded-prefix check.
  """
  use PhoenixKitWeb, :controller

  @app :phoenix_kit_catalogue
  @root "priv/static/pdfjs"

  # `.mjs` MUST carry a JS MIME or browsers refuse the ES module; the
  # rest pin types `MIME.from_path/1` may not know (`.bcmap`, `.ftl`).
  @content_types %{
    ".mjs" => "text/javascript",
    ".js" => "text/javascript",
    ".html" => "text/html",
    ".css" => "text/css",
    ".json" => "application/json",
    ".map" => "application/json",
    ".pdf" => "application/pdf",
    ".svg" => "image/svg+xml",
    ".png" => "image/png",
    ".gif" => "image/gif",
    ".bcmap" => "application/octet-stream",
    ".ftl" => "text/plain",
    ".pfb" => "application/octet-stream",
    ".otf" => "font/otf",
    ".ttf" => "font/ttf",
    ".woff" => "font/woff",
    ".woff2" => "font/woff2"
  }

  @doc """
  Streams a single vendored PDF.js asset by its path under
  `priv/static/pdfjs/`. 404s on traversal attempts, a missing
  catalogue app, or a non-file target.
  """
  def serve(conn, %{"path" => segments}) when is_list(segments) and segments != [] do
    with {:ok, abs} <- locate(segments),
         true <- File.regular?(abs) do
      conn
      |> put_resp_content_type(content_type(abs))
      |> put_resp_header("cache-control", "public, max-age=86400")
      |> send_file(200, abs)
    else
      _ -> send_resp(conn, 404, "Not found")
    end
  end

  def serve(conn, _params), do: send_resp(conn, 404, "Not found")

  # Resolve the request path under the catalogue app's vendored dir,
  # refusing anything that escapes it.
  defp locate(segments) do
    with {:ok, rel} <- Path.safe_relative(Path.join(segments)),
         base when is_binary(base) <- app_root() do
      abs = Path.join(base, rel)

      if String.starts_with?(Path.expand(abs), Path.expand(base) <> "/") do
        {:ok, abs}
      else
        :error
      end
    else
      _ -> :error
    end
  end

  defp app_root do
    Application.app_dir(@app, @root)
  rescue
    # Catalogue not loaded — the route shouldn't have been compiled in,
    # but stay defensive.
    ArgumentError -> :error
  end

  defp content_type(path) do
    ext = path |> Path.extname() |> String.downcase()
    Map.get(@content_types, ext) || MIME.from_path(path)
  end
end
