defmodule PhoenixKit.Install.MissingIgniter do
  @moduledoc """
  Recovery for the `mix phoenix_kit.*` tasks that cannot run without igniter.

  Igniter is an optional dependency (see `mix.exs`), and every task that drives
  it is wrapped in `if Code.ensure_loaded?(Igniter.Mix.Task)`. Without a
  fallback the guard's `else` branch defines nothing at all, so the task simply
  vanishes and Mix reports:

      ** (Mix) The task "phoenix_kit.update" could not be found

  which names neither PhoenixKit nor igniter, and leaves a host stranded on an
  old schema with nothing to search for. This module defines the stand-in task
  that takes its place, and — since the dep line is the same every time —
  offers to write it into the host's `mix.exs` instead of only describing it.

  ## Why the dep is optional at all

  A stock `mix phx.new` app declares `{:igniter, "~> 0.6", only: [:dev, :test]}`.
  A non-optional dep here resolves for all environments, and Mix refuses to
  converge the two — which broke `mix igniter.install phoenix_kit` on every
  freshly generated project. Optional means the host's own declaration wins.

  The cost is this case: a host that never declared igniter itself was getting
  it transitively, and an upgrade drops it. That is what this module covers.

  ## Why the compile-time guard is not enough

  `Code.ensure_loaded?/1` runs when PhoenixKit is compiled into the host's
  `_build`, and PhoenixKit is not recompiled when the host's own dependency
  list changes. Either side of the guard can therefore outlive the fact that
  chose it:

    * **Compiled with igniter, igniter since dropped.** The stale beam still
      takes the igniter branch, the `else` branch was never compiled, and the
      host gets `** (UndefinedFunctionError) function
      Igniter.Mix.Task.help_requested?/1 is undefined` out of the `run/1`
      generated by `use Igniter.Mix.Task`. Every igniter-backed task calls
      `ensure_available!/3` at the top of its own `run/1` to catch this.

    * **Compiled without igniter, igniter since added.** The stand-in below is
      still what Mix loads, so following its own advice appears to change
      nothing. `stand_in_run/2` detects that and asks for the one-line
      recompile instead of repeating the instructions.

  ## What it offers to do

  With igniter genuinely absent, `ensure_available!/3` prints the situation and
  asks to add `#{~s({:igniter, "~> 0.7", only: [:dev, :test]})}` to the host's
  `deps/0` (auto-accepted under `--yes`/`-y`), then shells out to `mix deps.get`
  — a fresh OS process, because the running one evaluated `mix.exs` at boot and
  will not see the new dep. It stops there rather than continuing: PhoenixKit
  itself has to be recompiled to pick the other side of the guard, which cannot
  happen inside the run that is already executing the wrong side. Declining, a
  MIX_ENV where `only: [:dev, :test]` would not help, an unparseable `deps/0`,
  or a failed fetch all fall back to the manual instructions.
  """

  @dep_line ~s({:igniter, "~> 0.7", only: [:dev, :test]})

  # `defp deps do` / `def deps() do` followed by the opening `[` on its own
  # line — the shape `mix new` and `mix phx.new` generate. Anything else (a
  # one-line list, a list built by a function call) is left alone: guessing at
  # someone's mix.exs is worse than printing the line for them to paste.
  @deps_head ~r/defp?[ \t]+deps(?:\(\))?[ \t]+do[ \t]*\n[ \t]*\[[ \t]*\n/

  @typedoc "Why the dep line could not be added automatically."
  @type failure ::
          :declined
          | :already_declared
          | :deps_not_found
          | :no_mix_exs
          | :fetch_failed
          | :unsupported_env

  @doc """
  Ensures igniter is loadable, or stops the task with the best available help.

  Called at the top of `run/1` in every igniter-backed task, and by the
  stand-in task this module defines. Returns `:ok` only when igniter is really
  there; every other outcome raises, because the caller's next move is code
  that cannot run.

  `argv` is the task's own arguments — `--yes`/`-y` skips the confirmation
  prompt. `igniter_module` exists so the failing branch is testable; callers
  pass the task name and argv only.
  """
  @spec ensure_available!(String.t(), [String.t()], module()) :: :ok
  def ensure_available!(task, argv \\ [], igniter_module \\ Igniter.Mix.Task) do
    if Code.ensure_loaded?(igniter_module) do
      :ok
    else
      offer_install!(task, argv)
    end
  end

  @doc """
  Body of the stand-in task, compiled in place of a task that needs igniter.

  Splits the two ways of arriving here: igniter is still missing (offer to add
  it), or it has since been added and only this stale module remembers
  otherwise (ask for the recompile).
  """
  @spec stand_in_run(String.t(), [String.t()]) :: no_return()
  def stand_in_run(task, argv) do
    if Code.ensure_loaded?(Igniter.Mix.Task) do
      Mix.raise(recompile_message(task))
    else
      ensure_available!(task, argv)
    end
  end

  @doc """
  The guidance printed when igniter is missing and cannot be added for us.

  `reason` names what stopped the automatic path, so the manual instructions
  can lead with the part that is actually different for this host.
  """
  @spec message(String.t(), failure() | nil) :: String.t()
  def message(task, reason \\ nil)

  # Declining answers a prompt that just explained all of this; only the part
  # the host still needs is worth repeating.
  def message(task, :declined) do
    """
    Nothing was changed. To do it by hand:

        #{@dep_line}

    then:

        mix deps.get
        mix #{task}
    """
  end

  # The dep line is already written; repeating "add it" would be wrong.
  def message(task, :fetch_failed) do
    """
    :igniter was added to mix.exs, but `mix deps.get` did not succeed — its output
    is above.

    Once that resolves:

        mix deps.get
        mix #{task}
    """
  end

  def message(task, reason) do
    """
    `mix #{task}` needs the :igniter dependency, which is not available in this project.

    #{reason_note(reason)}PhoenixKit declares igniter as an OPTIONAL dependency so that it converges with
    the `{:igniter, "~> 0.6", only: [:dev, :test]}` that `mix phx.new` generates.
    The trade-off is that a project which never declared igniter itself does not
    get it from PhoenixKit either.

    Add it to your mix.exs deps and re-run:

        #{@dep_line}

    then:

        mix deps.get
        mix #{task}

    Everything that does not generate or patch code — `mix phoenix_kit.status`,
    `mix phoenix_kit.gen.migration`, `mix phoenix_kit.assets.rebuild` — works
    without igniter and is unaffected.
    """
  end

  @doc """
  Inserts `#{@dep_line}` at the top of a `mix.exs` `deps/0` list.

  Returns the rewritten source, or `{:error, :already_declared}` when igniter
  is already in the list (a different problem — see `message/2`) and
  `{:error, :deps_not_found}` when the list is not in the shape the generators
  produce.
  """
  @spec add_igniter_dep(String.t()) :: {:ok, String.t()} | {:error, failure()}
  def add_igniter_dep(source) do
    if source =~ ~r/\{[ \t]*:igniter[ \t]*,/ do
      {:error, :already_declared}
    else
      insert_dep(source, Regex.run(@deps_head, source, return: :index))
    end
  end

  @doc """
  Body of the stand-in task. The caller supplies its own `@moduledoc` —
  generating one from here would hide it from static analysis.
  """
  defmacro __using__(opts) do
    task = Keyword.fetch!(opts, :task)
    helper = __MODULE__

    quote do
      use Mix.Task

      @shortdoc "Unavailable — requires the optional :igniter dependency"

      @impl Mix.Task
      def run(args), do: unquote(helper).stand_in_run(unquote(task), args)
    end
  end

  defp insert_dep(_source, nil), do: {:error, :deps_not_found}

  defp insert_dep(source, [{start, length}]) do
    # `return: :index` counts bytes, so the source must be split by bytes too.
    insert_at = start + length
    head = binary_part(source, 0, insert_at)
    tail = binary_part(source, insert_at, byte_size(source) - insert_at)

    {:ok, head <> indent_of(tail) <> @dep_line <> ",\n" <> tail}
  end

  # The indentation of the first entry already in the list, so the inserted
  # line lands where `mix format` would leave it.
  defp indent_of(tail) do
    case Regex.run(~r/\A([ \t]+)\S/, tail) do
      [_, indent] -> indent
      nil -> "      "
    end
  end

  defp offer_install!(task, argv) do
    with :ok <- check_env(),
         {:ok, source} <- read_mix_exs(),
         {:ok, updated} <- add_igniter_dep(source),
         :ok <- confirm(task, argv),
         :ok <- write_and_fetch(updated) do
      Mix.raise(rerun_message(task, argv))
    else
      {:error, reason} -> Mix.raise(message(task, reason))
    end
  end

  # The line this adds is `only: [:dev, :test]`, which would leave igniter just
  # as unavailable under any other MIX_ENV — writing it would look like progress
  # and change nothing.
  defp check_env do
    if Mix.env() in [:dev, :test], do: :ok, else: {:error, :unsupported_env}
  end

  defp read_mix_exs do
    case File.read("mix.exs") do
      {:ok, source} -> {:ok, source}
      {:error, _posix} -> {:error, :no_mix_exs}
    end
  end

  defp confirm(task, argv) do
    if "--yes" in argv or "-y" in argv or accepted?(task) do
      :ok
    else
      {:error, :declined}
    end
  end

  defp accepted?(task) do
    Mix.shell().info("""

    `mix #{task}` needs the :igniter dependency, which is not available here.
    PhoenixKit declares it as optional so that it converges with the igniter
    `mix phx.new` generates — a project that never declared it does not get it
    from PhoenixKit either.

    This adds one line to your mix.exs deps:

        #{@dep_line}
    """)

    Mix.shell().yes?("Add it and run mix deps.get?")
  end

  defp write_and_fetch(updated) do
    File.write!("mix.exs", updated)
    Mix.shell().info([:green, "* adding ", :reset, @dep_line, " to mix.exs"])
    fetch_deps()
  end

  # A fresh OS process: this one evaluated mix.exs at boot and its project
  # config no longer matches the file on disk.
  defp fetch_deps do
    case System.find_executable("mix") do
      nil ->
        {:error, :fetch_failed}

      mix ->
        Mix.shell().info([:green, "* running ", :reset, "mix deps.get"])

        case System.cmd(mix, ["deps.get"], stderr_to_stdout: true) do
          {output, 0} ->
            Mix.shell().info(output)
            :ok

          {output, _status} ->
            Mix.shell().error(output)
            {:error, :fetch_failed}
        end
    end
  end

  defp rerun_message(task, argv) do
    """
    :igniter is in mix.exs and fetched.

    PhoenixKit has to be recompiled against it before `mix #{task}` can run —
    that cannot happen inside this run, so it is one more command:

        mix #{Enum.join([task | argv], " ")}
    """
  end

  defp recompile_message(task) do
    """
    :igniter is available, but PhoenixKit was compiled without it and still has
    the stand-in version of `mix #{task}` — dependencies are not recompiled when
    the depending project's dependency list changes.

    Force it once:

        mix deps.compile phoenix_kit --force
        mix #{task}
    """
  end

  defp reason_note(:declined), do: "Nothing was changed.\n"

  defp reason_note(:already_declared),
    do: """
    :igniter is already declared in mix.exs, but it is not loadable in this MIX_ENV
    (#{Mix.env()}) — check its `only:` option, and that `mix deps.get` has run.

    """

  defp reason_note(:deps_not_found),
    do: """
    mix.exs does not have a `deps do [...]` list in the shape this task can edit,
    so the dependency has to be added by hand.

    """

  defp reason_note(:unsupported_env),
    do: """
    igniter is a dev-time dependency and this run is MIX_ENV=#{Mix.env()}, where
    `only: [:dev, :test]` would not make it available — so nothing was changed.
    Re-run with MIX_ENV=dev, or add the dependency for this environment yourself.

    """

  defp reason_note(:no_mix_exs),
    do: "mix.exs could not be read from #{File.cwd!()}.\n\n"

  defp reason_note(nil), do: ""
end
