defmodule PhoenixKit.Integration.ActivityOrderDeterminismTest do
  @moduledoc """
  Regression test for the `Activity.list/1` / `Activity.recent/1` tie-break bug:
  both sorted by `inserted_at` alone, which carries no uniqueness constraint.
  Two entries can still tie on it — rows written before V185 (`timestamp`
  went from second to microsecond precision) are all whole-second, which is
  the common case on any existing install, and even microsecond-precision
  writes can land on the identical instant. When they do, Postgres is free
  to return them in whichever order its query plan happened to land on — not
  necessarily the order they were actually created in.

  A tie cannot be reproduced by timing real `Activity.log/1` calls close
  together — it has to be forced by inserting rows with the SAME
  `inserted_at` explicitly (bypassing the schema's autogenerated timestamp
  via `insert_all/3`, since `Entry.changeset/2` does not cast it).

  """
  use PhoenixKit.DataCase, async: true

  alias PhoenixKit.Activity
  alias PhoenixKit.Activity.Entry

  defp insert_tied!(uuid, inserted_at) do
    {1, _} =
      Repo.insert_all(Entry, [
        %{
          uuid: uuid,
          action: "activity_order_determinism_test.tied",
          module: "activity_order_determinism_test",
          metadata: %{},
          inserted_at: inserted_at
        }
      ])

    uuid
  end

  test "recent/1 puts the truly-last entry first even when inserted_at ties" do
    # `:utc_datetime_usec` (the column's Ecto type) requires microsecond
    # precision on the struct even when the value itself is a whole second —
    # zero out the microseconds rather than truncating the precision away.
    tied_at = %{DateTime.utc_now() | microsecond: {0, 6}}
    ms = DateTime.to_unix(tied_at, :millisecond)

    # Same second, three different (and increasing) milliseconds — UUIDv7's
    # leading 48 bits are the millisecond timestamp, so `latest > middle >
    # earliest` byte-wise, exactly matching Postgres's `uuid` column
    # comparison.
    earliest = UUIDv7.generate(ms)
    middle = UUIDv7.generate(ms + 1)
    latest = UUIDv7.generate(ms + 2)

    # Three tied rows inserted middle, latest, earliest. Without the uuid
    # tiebreak Postgres returns ties in insertion order (seq scan + sort) or
    # its reverse (backward scan of the inserted_at index), and neither
    # equals [latest, middle, earliest]. With two rows one of those always
    # matches, so some plan would let the test pass without the fix.
    insert_tied!(middle, tied_at)
    insert_tied!(latest, tied_at)
    insert_tied!(earliest, tied_at)

    entries = Activity.recent(3)

    assert Enum.map(entries, & &1.uuid) == [latest, middle, earliest]
  end

  test "list/1 puts the truly-last entry first even when inserted_at ties" do
    tied_at = %{DateTime.utc_now() | microsecond: {0, 6}}
    ms = DateTime.to_unix(tied_at, :millisecond)

    earliest = UUIDv7.generate(ms)
    middle = UUIDv7.generate(ms + 1)
    latest = UUIDv7.generate(ms + 2)

    # Insert out of order — see the comment in the `recent/1` test above for
    # why.
    insert_tied!(middle, tied_at)
    insert_tied!(latest, tied_at)
    insert_tied!(earliest, tied_at)

    result =
      Activity.list(module: "activity_order_determinism_test", per_page: 3, preload: [])

    assert Enum.map(result.entries, & &1.uuid) == [latest, middle, earliest]
  end
end
